---
title: Histoires d'Harmonies - Exposition éphémère
timezone: UTC
collections:
  expo:
    title: Expo
    output: true
  exposition:
    title: Exposition
    output: true
  page:
    title: Page
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: pages
  values:
    layout: page
    images: 
    video: 
- scope:
    path: "/exposition/"
    type: expositions
  values:
    layout: exposition
    dates: 
    headline-image: 
    excerpt: 
    gallery-images: 
    videos: 
    audio: 
env: production
host: localhost
port: 8000
process: 3003
keep_files:
- assets
baseurl: ''
url: "."
email: jcf@xxi.fr
description: ''
twitter_username: XXI_com
github_username: xxidigital
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- package.json
- gulpfile.js
- README.md
- node_modules
- yarn.lock
- _process
- _static
