---
title: Histoires d'Harmonies - Exposition éphémère
timezone: UTC
collections:
  exposition:
    title: Exposition
    output: true
    permalink: "/:collection/:title.html"
  posts:
    title: Posts
    output: true
  quiz:
    title: Quiz
    output: true
    permalink: "/:collection/:title"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: exposition
    type: exposition
  values:
    headline-image: 
    dates: 
    galerie-images: 
    videos:
    - image: 
      url: 
      titre: 
      durée: 
    audio:
      reference: 
      url: 
      titre: 
    layout: exposition
- scope:
    path: quiz
    type: quiz
  values:
    reponse: 
    choix:
      label: 
    layout: quiz
host: localhost
port: 8000
process: 3003
keep_files:
- assets
baseurl: 
url: "."
analytics: UA-XXXXX-Y
email: jcf@xxi.fr
description: 
twitter_username: XXI_com
github_username: xxidigital
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- package.json
- gulpfile.js
- README.md
- node_modules
- yarn.lock
- _process
- _static
