---
title: Histoires d'Harmonies - Exposition éphémère
timezone: UTC
collections:
  exposition:
    title: Exposition
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: exposition
    type: exposition
  values:
    headline-image:
    dates:
    gallery-images:
    videos:
    - image:
      url:
      titre:
      durée:
    layout: exposition
env: production
host: localhost
port: 8000
process: 3003
keep_files:
- assets
baseurl:
url: "."
email: jcf@xxi.fr
description:
twitter_username: XXI_com
github_username: xxidigital
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- package.json
- gulpfile.js
- README.md
- node_modules
- yarn.lock
- _process
- _static
